name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tag: 

jobs:
  login: 
    runs-on: ubuntu-latest
    steps:
    - env: ${{ secrets.key }}
      run: echo "${{ secrets.key }}"
      name: private key
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: docker build -t quelpoke .
  
 
    
